TheThreeProjections.pdf: TheThreeProjections.lhs compiling.png dollar_minting.png general_minting.png projection1.png projection2a.png projection3.png specialisation.png
	lhs2tex -verb TheThreeProjections.lhs > TheThreeProjections.tex
	pdflatex TheThreeProjections.tex
